services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: inmobiscrap_frontend
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    restart: unless-stopped
